baseurl = "https://mailund.github.io/r-programmer-blog/"
title = "The Working R Programmer"
copyright = "Copyright &copy; 2018 - Thomas Mailund"
theme = "hugo-kiera"

publishDir = "docs"

canonifyurls = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

googleAnalytics = "UA-126024558-1"
disqusShortname = "r-programmer-blog"

paginate = 20
summaryLength = 30
pygmentsCodeFences = true
pygmentsStyle = "native"


[author]
    name = "Thomas Mailund"
    github = "mailund"
    twitter = "ThomasMailund"
    linkedin = "thomas-mailund-94153b1"
    facebook = "mailund"
    patreon = "mailund"
    goodreads = "15484380.Thomas_Mailund"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    tagline = "Tips and tricks for serious software development in R"

    googlefonts = ["Droid Sans", "Fira Code"]
    fontbody = 'Droid Sans'
    fontcode = 'Fira Code'
